"""create users and reports tables

Revision ID: 59635b58d3b1
Revises: c01830d0ca0f
Create Date: 2025-05-07 17:09:57.550479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59635b58d3b1'
down_revision: Union[str, None] = 'c01830d0ca0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
